# Profiling Poverty and Land Use in three U.S Cities
Authors: Clayton Coffman, Chris Joyce, Adam Miner

In [1]:
#Imports
import pandas as pd
import matplotlib.pyplot as plt
import geopandas

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
from sklearn.cluster import DBSCAN, KMeans

%matplotlib inline

In [3]:
#Bring in the datasets, the three csvs of US cities
seattle_df = pd.read_csv("seattle_ltdb_nanda.csv")
nyc_df = pd.read_csv("nyc_ltdb_nanda.csv")
dc_df = pd.read_csv("dc_ltdb_nanda.csv")

The way to use a clustering algorithm to create clusters of poverty and land use is to:
- Segment the cities (done)
- Seperate the years and standard scale them (done)
- Combine everything together (done)
- Cluster (in this notebook)
- Analyze and evaluate clusters (in this notebook)
- EDA (maybe in this notebook?)

In [4]:
seattle_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2151 entries, 0 to 2150
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          2151 non-null   int64
 1   tractid             2151 non-null   int64
 2   tract               2151 non-null   object
 3   county              2151 non-null   object
 4   state               2151 non-null   object
 5   year                2151 non-null   int64
 6   GEOID10             2151 non-null   int64
 7   NAMELSAD10          2151 non-null   object
 8   tractid_nanda       2151 non-null   int64
 9   year_nanda          2151 non-null   int64
 10  pop                 2151 non-null   float64
 11  incpc               2151 non-null   float64
 12  ppov                2151 non-null   float64
 13  hinc                2151 non-null   float64
 14  phs                 2151 non-null   float64
 15  mrent               2151 non-null   float64
 16  mhmval              2151 non-null   float64
 17  pown                2151 non-null   float64
 18  pmulti              2151 non-null   float64
 19  open_urban_space    2151 non-null   float64
 20  low_development     2151 non-null   float64
 21  medium_development  2151 non-null   float64
 22  high_development    2151 non-null   float64
 23  unclassified        2151 non-null   float64
 24  forested            2151 non-null   float64
 25  cultivated          2151 non-null   float64
dtypes: float64(16), int64(6), object(4)
memory usage: 437.0+ KB

### What are we looking for

We will be searching for clusters of potential abject poverty indicators in the socioeconomic, census-based variables. These will be values with very low standardized scores (i.e. centroids of clusters below the mean, with the exception of population, unclear what that one needs to be). We'll only be focusing on those clusters. The EDA portion will analyze the differences between cities in the data in these clusters, and then how the land cover proportion of census tracts is different in these clusters between these cities.

In [5]:
##potential values to pull out to tune the model more - 'pop', 'incpc', 'hinc', 'phs', 'mrent', 'mhmval', 'pown', 'pmulti'
X_sea = seattle_df.drop(columns = ['Unnamed: 0', 'tractid', 'tract', 'county', 'state', 'year', 'GEOID10', 'NAMELSAD10', 'tractid_nanda', 'year_nanda'])
X_nyc = nyc_df.drop(columns = ['Unnamed: 0', 'tractid', 'tract', 'county', 'state', 'year', 'GEOID10', 'NAMELSAD10', 'tractid_nanda', 'year_nanda'])
X_dc = dc_df.drop(columns = ['Unnamed: 0', 'tractid', 'tract', 'county', 'state', 'year', 'GEOID10', 'NAMELSAD10', 'tractid_nanda', 'year_nanda'])

In [6]:
# Use that "gridsearch" way of pulling best clusters out to identify the best number of clusters to fit
#Seattle first
scores = []

for k in range(2, 12):
    cl = KMeans(n_clusters=k, random_state=42)
    cl.fit(X_sea)
    inertia = cl.inertia_
    sil = silhouette_score(X_sea, cl.labels_)
    
    scores.append([k, inertia, sil])
    
score_df = pd.DataFrame(scores)
score_df.columns = ['k', 'inertia', 'silhouette_score']

D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [7]:
score_df # Eight clusters seems to fit Seattle the best, though it's not fantastic (not bad though, just meh)

    k       inertia  silhouette_score
0   2  27414.885878          0.189567
1   3  24085.129138          0.167118
2   4  21296.343885          0.177965
3   5  19425.127481          0.171628
4   6  17996.506238          0.176522
5   7  16865.819270          0.186788
6   8  15920.616271          0.189820
7   9  15163.591102          0.155965
8  10  14556.230370          0.152528
9  11  14021.192380          0.153721

In [8]:
km = KMeans(n_clusters=8, random_state=42)
km.fit(X_sea)
seattle_df['cluster'] = km.predict(X_sea)

D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [9]:
seattle_df.head()

,Unnamed: 0,tractid,tract,county,state,year,GEOID10,NAMELSAD10,tractid_nanda,year_nanda,...,pown,pmulti,open_urban_space,low_development,medium_development,high_development,unclassified,forested,cultivated,cluster
0,0,53053062000,Census Tract 620,Pierce County,WA,2000,53053062000,Census Tract 620,53053062000,2000,...,-0.399685,-0.081674,-0.115412,-0.114837,1.936730,-0.303959,-0.504936,-0.698798,-0.394941,4
1,1,53053062000,Census Tract 620,Pierce County,Washington,2012,53053062000,Census Tract 620,53053062000,2012,...,0.082124,-0.068814,-0.177950,-0.127693,1.968619,-0.290302,-0.568763,-0.669075,-0.372462,4
2,2,53053062000,Census Tract 620,Pierce County,Washington,2019,53053062000,Census Tract 620,53053062000,2019,...,-0.317821,-0.346802,-0.219495,-0.131986,1.979176,-0.285249,-0.565955,-0.665589,-0.369772,4
3,3,53053071601,Census Tract 716.01,Pierce County,WA,2000,53053071601,Census Tract 716.01,53053071601,2000,...,-0.604169,0.367697,2.697094,0.665428,-0.324241,-0.243008,-0.519012,-0.725305,-0.336405,4
4,4,53053071601,Census Tract 716.01,Pierce County,Washington,2012,53053071601,Census Tract 716.01,53053071601,2012,...,-0.716442,0.224066,2.548283,0.619144,-0.252100,-0.231743,-0.494155,-0.710402,-0.310311,4

In [10]:
seattle_df.drop(columns = ['Unnamed: 0', 'tractid', 'tract', 'county', 'state', 'year', 'GEOID10', 'NAMELSAD10', 'tractid_nanda', 'year_nanda']).groupby('cluster').mean()

,pop,incpc,ppov,hinc,phs,mrent,mhmval,pown,pmulti,open_urban_space,low_development,medium_development,high_development,unclassified,forested,cultivated
cluster,,,,,,,,,,,,,,,,
0,-0.467653,0.165520,1.830175,-1.116742,-0.260143,-0.408301,0.005099,-1.879045,2.243930,-1.306729,-1.577952,0.118349,3.390396,-0.019293,-0.735566,-0.274732
1,0.173396,-0.237888,-0.371952,0.079446,0.092848,0.076797,-0.308753,0.438569,-0.418154,0.742669,0.631007,-0.169765,-0.369356,-0.254659,-0.125612,-0.183005
2,0.138806,0.723727,-0.237689,0.203820,-1.050128,0.286062,0.731495,-0.198562,0.504782,-0.727166,0.303187,1.039335,0.150010,-0.326816,-0.496235,-0.314817
3,-0.416090,-0.060599,-0.489502,0.298761,0.169581,-0.172169,-0.078584,0.308532,-0.897567,-0.158616,-1.333777,-1.317345,-0.613117,0.168365,2.247222,0.232255
4,0.042830,-0.892908,0.909896,-0.995169,1.012027,-0.776861,-0.786124,-0.633923,0.623742,-0.239407,0.125636,0.799963,0.357373,-0.348565,-0.558283,-0.217812
5,-0.241019,1.448563,-0.343550,0.818083,-0.980841,0.558877,1.450454,0.148284,-0.019872,-0.741765,-0.626987,-0.656532,-0.389000,3.374155,-0.515406,-0.280869
6,0.092011,1.487282,-0.846744,1.934358,-1.246624,1.675455,1.573110,0.829207,-0.784699,0.612080,0.300553,-0.694320,-0.565541,0.029648,0.538690,-0.222910
7,-0.255791,-0.430354,-0.251497,-0.105881,0.688350,-0.357419,-0.449846,0.421675,-0.687399,-0.267123,-0.946039,-1.042669,-0.536726,0.331954,0.331597,3.889535

Very quick way to find poverty clusters is to see the high values of ppov. There are two clusters that really take the cake for it, cluster 0 and cluster 4. So let's look at these ones to pick out the differences between them.

Cluster 0 is low population, average per capita income, low household income, lower than average high school grads, low rent value, average home values, very low home ownership, very high multi-home living. The census tracts they belong in are very very high developed areas, signifying a city, with very low forested and agricultural land.

Cluster 4 is average population, very low income per capita, household income, but has a high number of high school graduates, rent and home values are low, and not a lot of people own homes. Higher than average people live in multi-family dwellings, but not as many as cluster 0. Noteworthy is that they are mainly living in medium development areas, so likely lower-class suburbs.

I wanted to point out Cluster 7, which are probably more rural poor tracts. They don't have as many people living in poverty, but they do have low levels of income, and high levels of home ownership, so it is a different kind of poverty than people living closer into the MSA.

In [11]:
# Use that "gridsearch" way of pulling best clusters out to identify the best number of clusters to fit
#NYC
scores = []

for k in range(2, 12):
    cl = KMeans(n_clusters=k, random_state=42)
    cl.fit(X_nyc)
    inertia = cl.inertia_
    sil = silhouette_score(X_nyc, cl.labels_)
    
    scores.append([k, inertia, sil])
    
score_df = pd.DataFrame(scores)
score_df.columns = ['k', 'inertia', 'silhouette_score']

D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [12]:
score_df #bit better than Seattle, 4 clusters seem to be optimal. I'm going to do 8 to see if it also picks out a rural poor, because 4 didnt

    k        inertia  silhouette_score
0   2  168292.977489          0.253769
1   3  150488.468499          0.246329
2   4  134777.494947          0.225155
3   5  123023.120460          0.180577
4   6  114306.200275          0.195825
5   7  105891.129621          0.184788
6   8   98769.505446          0.183757
7   9   92583.048692          0.190790
8  10   89145.560335          0.183244
9  11   86274.721287          0.170230

In [13]:
km = KMeans(n_clusters=8, random_state=42)
km.fit(X_nyc)
nyc_df['cluster'] = km.predict(X_nyc)

D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [14]:
nyc_df.drop(columns = ['Unnamed: 0', 'tractid', 'tract', 'county', 'state', 'year', 'GEOID10', 'NAMELSAD10', 'tractid_nanda', 'year_nanda']).groupby('cluster').mean()

,pop,incpc,ppov,hinc,phs,mrent,mhmval,pown,pmulti,open_urban_space,low_development,medium_development,high_development,unclassified,forested,cultivated
cluster,,,,,,,,,,,,,,,,
0,0.145223,0.286397,-0.677469,0.583645,-0.485739,-0.145238,-0.317809,0.526291,-1.125359,0.115770,-0.543027,-1.247076,-1.004389,0.441161,2.703905,2.398607
1,-0.225722,0.077910,-0.324951,-0.017518,-0.189864,-0.092080,-0.285470,-0.239142,-0.276868,-0.257602,-0.356853,-0.736879,-0.689750,2.967795,0.048967,-0.138060
2,0.136503,-0.896692,1.682231,-1.155344,1.190709,-0.929202,-0.558724,-0.959502,0.970452,-0.512848,-0.313316,0.505542,0.454784,-0.305476,-0.397686,-0.220794
3,-0.133005,-0.179236,-0.340403,-0.019265,0.026177,0.052047,-0.171235,0.299090,-0.174442,-0.473218,0.052957,1.394126,-0.207683,-0.394196,-0.447235,-0.233992
4,0.199591,0.025685,-0.542320,0.246766,-0.205693,0.033925,-0.418449,0.529084,-0.711423,0.963411,1.402874,-0.306733,-0.848632,-0.074424,0.019840,-0.122496
5,-0.364088,-0.436003,0.290528,-0.546284,0.413468,-0.168561,0.300436,-0.383908,0.788822,-0.723099,-0.880077,-0.288522,1.401047,-0.449204,-0.456241,-0.237414
6,0.283374,1.367871,-0.852775,1.862095,-1.358268,1.190046,1.031468,0.909550,-1.175158,1.903447,0.489596,-0.932143,-0.955096,0.189543,0.628233,-0.048848
7,0.391546,2.714720,-0.457781,1.161033,-1.774202,1.847079,2.084685,-0.647546,1.196189,-0.629574,-0.747311,-0.120481,0.859904,0.171847,-0.390570,-0.234165

Cluster 7 seems to be a highly impoverished core in the most developed parts of the New York MSA. The scores are almost universally negative values, signifying low on most variables, and living in multi-family homes.

Noteworthy is that the rural clusters, Clusters 0, 6, does not seem to be impoverished (ppov is low), and like Seattle has really high rates of home ownership. There doesn't seem to be a good rural poor cluster in the NYC MSA.

In [15]:
# Use that "gridsearch" way of pulling best clusters out to identify the best number of clusters to fit
#DC
scores = []

for k in range(2, 12):
    cl = KMeans(n_clusters=k, random_state=42)
    cl.fit(X_dc)
    inertia = cl.inertia_
    sil = silhouette_score(X_dc, cl.labels_)
    
    scores.append([k, inertia, sil])
    
score_df = pd.DataFrame(scores)
score_df.columns = ['k', 'inertia', 'silhouette_score']

D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [16]:
score_df #DC seems to perform best with four clusters

    k       inertia  silhouette_score
0   2  51436.214022          0.208646
1   3  43749.970873          0.207907
2   4  38724.252620          0.213372
3   5  34492.750434          0.193140
4   6  32364.741398          0.196001
5   7  30438.874198          0.176374
6   8  28973.479267          0.178852
7   9  27590.654466          0.178445
8  10  26389.867267          0.161729
9  11  25616.410755          0.157045

In [17]:
km = KMeans(n_clusters=8, random_state=42)
km.fit(X_dc)
dc_df['cluster'] = km.predict(X_dc)

D:\Anaconda\envs\dsi_spatial\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [18]:
dc_df.drop(columns = ['Unnamed: 0', 'tractid', 'tract', 'county', 'state', 'year', 'GEOID10', 'NAMELSAD10', 'tractid_nanda', 'year_nanda']).groupby('cluster').mean()

,pop,incpc,ppov,hinc,phs,mrent,mhmval,pown,pmulti,open_urban_space,low_development,medium_development,high_development,unclassified,forested,cultivated
cluster,,,,,,,,,,,,,,,,
0,0.317063,-0.032522,-0.402864,0.241438,-0.309760,0.337858,-0.070496,0.521786,-0.471202,0.680955,0.533844,-0.325812,-0.324522,-0.150154,-0.102079,-0.278321
1,-0.427633,0.823717,0.132275,-0.133402,-0.819058,0.319210,0.365698,-0.940836,1.409772,-1.211325,-0.661311,1.653416,2.045272,-0.372518,-0.952899,-0.418857
2,-0.345459,-1.207638,2.621392,-1.445067,1.548978,-1.174166,-0.733170,-1.707795,1.164233,-0.774160,0.139610,1.424506,0.632865,-0.171644,-0.883895,-0.415557
3,-0.198150,-0.144750,-0.380921,0.083804,0.213848,-0.581293,-0.077782,0.478632,-0.746236,-0.849217,-1.293222,-0.913402,-0.508695,-0.121811,0.592285,2.964261
4,-0.007959,-0.643634,0.322834,-0.782839,0.648224,-0.440765,-0.608617,-0.454442,0.615946,0.046419,0.675119,0.390752,-0.008127,-0.323867,-0.504038,-0.360300
5,-0.018477,-0.291015,-0.350709,0.007290,0.358791,-0.484887,-0.348766,0.397362,-0.739820,-0.618997,-1.122031,-0.856902,-0.475370,0.592066,1.851318,0.290647
6,-0.319226,-0.223561,-0.111746,-0.315688,0.182242,-0.224968,-0.475468,-0.195377,-0.129423,-0.621610,-0.797882,-0.535926,-0.314982,4.354230,-0.031247,-0.153698
7,0.062295,1.653720,-0.623913,1.785558,-1.203724,1.326683,1.844253,0.709561,-0.626336,1.075803,0.126335,-0.562446,-0.394163,-0.096552,0.246513,-0.353206

Like NYC, I cannot pick out a rural poor cluster in the DC MSA. Three clusters are almost distinctly poor tracts in cities, suburbs, and more sparse suburbs (but probably not rural areas). The rural clusters (3 and 5) are almost identical to the other rural census tracts in home ownership, but all are not poor in the same way that Seattle MSA has a cluster of poor rural areas.

In [3]:
#Export these clusters to csv
seattle_df.to_csv('seattle_clusters.csv', index = False)
nyc_df.to_csv('nyc_clusters.csv', index = False)
dc_df.to_csv('dc_clusters.csv', index = False)

NameError: name 'seattle_df' is not defined

## Exploratory Data Analysis Using Markov Chains and Spatial Analysis

**To Do Here**

- Make Markov Chain transition. This is essentially a table that shows the proportion of clusters that occupy each space in that snapshot, and how that changes through time. An example is if in the year 2000, Seattle's Cluster 7 accounts for 50 percent of the total census tract in the MSA, and then by 2019 Cluster 7 accounts for 40 percent, we could determine that the evolution of the MSA landscape in Seattle is going away from the rural poor areas.
- Spatial EDA. Plot the clusters' locations on a map, to figure out contiguity, identify geographic clusters, and establish if there is a spatial relationship between clusters, to help profile the full MSA as well as pockets of Cluster profiles within the MSA.

In [2]:
#Adam's part: Markov Chain Matrix
#It's not a true Markov Chain model, but instead we're coopting the use of the matrix to create a table of transitions
#This will be the plot of part of the whole over each snapshot in time

#Bring in the just exported datasets, the three csvs of US cities
seattle_clusters = pd.read_csv("./data/seattle_clusters.csv")
nyc_clusters = pd.read_csv("./data/nyc_clusters.csv")
dc_clusters = pd.read_csv("./data/dc_clusters.csv")

In [3]:
#Get the value counts (normalized) for each csv's snapshot in time
#create markov dataframe for each city
seattle_mk_df = pd.DataFrame()
nyc_mk_df = pd.DataFrame()
dc_mk_df = pd.DataFrame()

In [4]:
# Organize the new table by proportion of cluster

for i in seattle_clusters['year'].unique():
    seattle_mk_df[i] = seattle_clusters[seattle_clusters['year'] == i]['cluster'].value_counts(normalize=True)
    
for i in nyc_clusters['year'].unique():
    nyc_mk_df[i] = nyc_clusters[nyc_clusters['year'] == i]['cluster'].value_counts(normalize=True)

for i in dc_clusters['year'].unique():
    dc_mk_df[i] = dc_clusters[dc_clusters['year'] == i]['cluster'].value_counts(normalize=True)

In [5]:
seattle_mk_df

       2000      2012      2019
1  0.321678  0.288301  0.317549
4  0.222378  0.235376  0.222841
2  0.120280  0.142061  0.137883
3  0.116084  0.097493  0.098886
6  0.079720  0.093315  0.077994
7  0.048951  0.041783  0.040390
5  0.046154  0.051532  0.051532
0  0.044755  0.050139  0.052925

These are the Markov Chains ^^ and let's look at the changes in them. The only noteworthy thing is that Cluster 3 seems to be decreasing over time, though it had plateaued in 2019. Cluster 3 seems to be more forested census tracts, so it seemingly has lost land to development in other clusters. Cluster 1, which is mainly low density urban space, seemed to take this, signifying some early development of more heavily forested census tracts.

In [6]:
nyc_mk_df

     2000.0    2012.0    2019.0
5  0.261828  0.239293  0.250160
1  0.238707  0.240358  0.235244
7  0.169985  0.193906  0.180908
2  0.131235  0.140422  0.132538
4  0.074716  0.069891  0.074153
3  0.054806  0.047731  0.049435
0  0.044316  0.044961  0.053697
6  0.024406  0.023439  0.023865

Cluster 7, the impoverished urban inner core, seems to have marginally increased over time. It could mean that more urban areas have transitioned to this type of profile, or the areas in the NY MSA just improved across the board and dropped more census tracts into this category in later years.

In [7]:
dc_mk_df

       2000      2012      2019
0  0.277286  0.264901  0.261957
4  0.207965  0.229581  0.232524
5  0.126106  0.107432  0.114054
7  0.121681  0.126564  0.120677
3  0.089971  0.077263  0.072848
1  0.076696  0.102281  0.113319
2  0.071534  0.066961  0.060338
6  0.028761  0.025018  0.024283

DC has a few more noteworthy transitions. Cluster 4, the suburban less-developed areas, has increased, likely as that urban sprawl has enveloped more census tracts in the MSA. In addition, Cluster 3, the profile of sparsely populated forested and agricultural areas has decreased, signifying transitions into more urbanized spaces in these former lands. Finally Cluster 1 has increased and Cluster 2 has decreased. The dilineation between these urbanized poor areas is how developed the census tracts are. Cluster 1 increasing signifies the MSA having more numerous urban inner core poor areas, and less numerous populated outer core areas.

In [11]:
# pip install -U datapane #Uncomment this if you need to install it for the interactive tables

Collecting datapane
  Using cached datapane-0.16.4-py3-none-any.whl (226 kB)
Collecting furl<3.0.0,>=2.0.0
  Using cached furl-2.1.3-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: packaging<24.0.0,>=21.0.0 in d:\anaconda (from datapane) (23.0)
Requirement already satisfied: pandas<2.0.0,>=1.1.0 in d:\anaconda\lib\site-packages (from datapane) (1.4.4)
Requirement already satisfied: importlib_resources<6.0.0,>=3.0.0 in d:\anaconda\lib\site-packages (from datapane) (5.12.0)
Collecting dulwich<0.22.0,>=0.20.0
  Using cached dulwich-0.21.5-cp39-cp39-win_amd64.whl
Collecting dacite<2.0.0,>=1.0.2
  Using cached dacite-1.8.0-py3-none-any.whl (14 kB)
Requirement already satisfied: boltons<22.0.0,>=20.0.0 in d:\anaconda\lib\site-packages (from datapane) (21.0.0)
Requirement already satisfied: requests<3.0.0,>=2.19.0 in d:\anaconda\lib\site-packages (from datapane) (2.28.1)
Collecting datacommons<2.0.0,>=1.4.3
  Using cached datacommons-1.4.3-py3-none-any.whl (46 kB)
Collecting vega-datasets<1.0.0,>=0.9.0
  Using cached vega_datasets-0.9.0-py3-none-any.whl (210 kB)
Collecting requests-toolbelt<0.11.0,>=0.9.1
  Using cached requests_toolbelt-0.10.1-py2.py3-none-any.whl (54 kB)
Requirement already satisfied: click-spinner<0.2.0,>=0.1.8 in d:\anaconda\lib\site-packages (from datapane) (0.1.10)
Collecting colorlog<7.0.0,>=4.1.0
  Using cached colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Collecting cheroot<10.0.0,>=9.0.0
  Using cached cheroot-9.0.0-py2.py3-none-any.whl (100 kB)
Requirement already satisfied: pyarrow<11.0.0,>=6.0.0 in d:\anaconda\lib\site-packages (from datapane) (10.0.1)
Requirement already satisfied: pydantic<2.0.0,>=1.6.0 in d:\anaconda\lib\site-packages (from datapane) (1.10.2)
Requirement already satisfied: lxml<5.0.0,>=4.0.0 in d:\anaconda\lib\site-packages (from datapane) (4.9.1)
Requirement already satisfied: jsonschema<5.0.0,>=3.2.0 in d:\anaconda\lib\site-packages (from datapane) (4.16.0)
Collecting posthog<3.0.0,>=1.4.0
  Using cached posthog-2.5.0-py2.py3-none-any.whl (36 kB)
Requirement already satisfied: tabulate<0.10.0,>=0.8.9 in d:\anaconda\lib\site-packages (from datapane) (0.8.10)
Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in d:\anaconda (from datapane) (4.5.0)
Collecting ipynbname<2022.0.0,>=2021.3.2
  Using cached ipynbname-2021.3.2-py3-none-any.whl (4.0 kB)
Requirement already satisfied: pyngrok<6.0.0,>=5.2.1 in d:\anaconda\lib\site-packages (from datapane) (5.2.3)
Collecting glom<24.0.0,>=22.1.0
  Using cached glom-23.3.0-py3-none-any.whl (101 kB)
Requirement already satisfied: micawber>=0.5.0 in d:\anaconda\lib\site-packages (from datapane) (0.5.4)
Requirement already satisfied: chardet<6.0.0,>=4.0.0 in d:\anaconda\lib\site-packages (from datapane) (4.0.0)
Collecting multimethod<2.0,>=1.9
  Using cached multimethod-1.9.1-py3-none-any.whl (10 kB)
Requirement already satisfied: nbconvert>=5.6.1 in d:\anaconda\lib\site-packages (from datapane) (6.4.4)
Collecting dominate<3.0.0,>=2.4.0
  Using cached dominate-2.7.0-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: PyYAML<7.0.0,>=5.4.0 in d:\anaconda\lib\site-packages (from datapane) (6.0)
Collecting datacommons-pandas<0.0.4,>=0.0.3
  Using cached datacommons_pandas-0.0.3-py3-none-any.whl (45 kB)
Requirement already satisfied: click<9.0.0,>=7.1.0 in d:\anaconda\lib\site-packages (from datapane) (8.0.4)
Requirement already satisfied: toolz<0.13.0,>=0.11.0 in d:\anaconda\lib\site-packages (from datapane) (0.11.2)
Requirement already satisfied: altair<5.0.0,>=4.0.0 in d:\anaconda\lib\site-packages (from datapane) (4.2.2)
Requirement already satisfied: jinja2 in d:\anaconda\lib\site-packages (from altair<5.0.0,>=4.0.0->datapane) (2.11.3)
Requirement already satisfied: entrypoints in d:\anaconda\lib\site-packages (from altair<5.0.0,>=4.0.0->datapane) (0.4)
Requirement already satisfied: numpy in d:\anaconda\lib\site-packages (from altair<5.0.0,>=4.0.0->datapane) (1.23.5)
Collecting jaraco.functools
  Using cached jaraco.functools-3.6.0-py3-none-any.whl (7.9 kB)
Collecting more-itertools>=2.6
  Using cached more_itertools-9.1.0-py3-none-any.whl (54 kB)
Requirement already satisfied: six>=1.11.0 in d:\anaconda\lib\site-packages (from cheroot<10.0.0,>=9.0.0->datapane) (1.16.0)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from click<9.0.0,>=7.1.0->datapane) (0.4.5)
Requirement already satisfied: urllib3>=1.25 in d:\anaconda\lib\site-packages (from dulwich<0.22.0,>=0.20.0->datapane) (1.26.11)
Collecting orderedmultidict>=1.0.1
  Using cached orderedmultidict-1.0.1-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: attrs in d:\anaconda\lib\site-packages (from glom<24.0.0,>=22.1.0->datapane) (21.4.0)
Collecting face==20.1.1
  Using cached face-20.1.1-py3-none-any.whl (51 kB)
Requirement already satisfied: zipp>=3.1.0 in d:\anaconda (from importlib_resources<6.0.0,>=3.0.0->datapane) (3.15.0)
Requirement already satisfied: ipykernel in d:\anaconda\lib\site-packages (from ipynbname<2022.0.0,>=2021.3.2->datapane) (6.15.2)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in d:\anaconda\lib\site-packages (from jsonschema<5.0.0,>=3.2.0->datapane) (0.18.0)
Requirement already satisfied: pandocfilters>=1.4.1 in d:\anaconda\lib\site-packages (from nbconvert>=5.6.1->datapane) (1.5.0)
Requirement already satisfied: testpath in d:\anaconda\lib\site-packages (from nbconvert>=5.6.1->datapane) (0.6.0)
Requirement already satisfied: pygments>=2.4.1 in d:\anaconda\lib\site-packages (from nbconvert>=5.6.1->datapane) (2.14.0)
Requirement already satisfied: defusedxml in d:\anaconda\lib\site-packages (from nbconvert>=5.6.1->datapane) (0.7.1)
Requirement already satisfied: beautifulsoup4 in d:\anaconda\lib\site-packages (from nbconvert>=5.6.1->datapane) (4.11.1)
Requirement already satisfied: jupyter-core in d:\anaconda\lib\site-packages (from nbconvert>=5.6.1->datapane) (4.11.1)
Requirement already satisfied: traitlets>=5.0 in d:\anaconda\lib\site-packages (from nbconvert>=5.6.1->datapane) (5.1.1)
Requirement already satisfied: nbformat>=4.4 in d:\anaconda\lib\site-packages (from nbconvert>=5.6.1->datapane) (5.5.0)
Requirement already satisfied: bleach in d:\anaconda\lib\site-packages (from nbconvert>=5.6.1->datapane) (4.1.0)
Requirement already satisfied: jupyterlab-pygments in d:\anaconda\lib\site-packages (from nbconvert>=5.6.1->datapane) (0.1.2)
Requirement already satisfied: mistune<2,>=0.8.1 in d:\anaconda\lib\site-packages (from nbconvert>=5.6.1->datapane) (0.8.4)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in d:\anaconda\lib\site-packages (from nbconvert>=5.6.1->datapane) (0.5.13)
Requirement already satisfied: python-dateutil>=2.8.1 in d:\anaconda\lib\site-packages (from pandas<2.0.0,>=1.1.0->datapane) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas<2.0.0,>=1.1.0->datapane) (2022.1)
Collecting backoff>=1.10.0
  Using cached backoff-2.2.1-py3-none-any.whl (15 kB)
Requirement already satisfied: monotonic>=1.5 in d:\anaconda\lib\site-packages (from posthog<3.0.0,>=1.4.0->datapane) (1.6)
Requirement already satisfied: charset-normalizer<3,>=2 in d:\anaconda\lib\site-packages (from requests<3.0.0,>=2.19.0->datapane) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests<3.0.0,>=2.19.0->datapane) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests<3.0.0,>=2.19.0->datapane) (2022.9.14)
Requirement already satisfied: MarkupSafe>=0.23 in d:\anaconda\lib\site-packages (from jinja2->altair<5.0.0,>=4.0.0->datapane) (2.0.1)
Requirement already satisfied: jupyter-client>=6.1.5 in d:\anaconda\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert>=5.6.1->datapane) (7.3.4)
Requirement already satisfied: nest-asyncio in d:\anaconda\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert>=5.6.1->datapane) (1.5.5)
Requirement already satisfied: fastjsonschema in d:\anaconda\lib\site-packages (from nbformat>=4.4->nbconvert>=5.6.1->datapane) (2.16.2)
Requirement already satisfied: soupsieve>1.2 in d:\anaconda\lib\site-packages (from beautifulsoup4->nbconvert>=5.6.1->datapane) (2.3.1)
Requirement already satisfied: webencodings in d:\anaconda\lib\site-packages (from bleach->nbconvert>=5.6.1->datapane) (0.5.1)
Requirement already satisfied: psutil in d:\anaconda\lib\site-packages (from ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (5.9.0)
Requirement already satisfied: ipython>=7.23.1 in d:\anaconda\lib\site-packages (from ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (7.31.1)
Requirement already satisfied: pyzmq>=17 in d:\anaconda\lib\site-packages (from ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (23.2.0)
Requirement already satisfied: tornado>=6.1 in d:\anaconda\lib\site-packages (from ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (6.1)
Requirement already satisfied: matplotlib-inline>=0.1 in d:\anaconda\lib\site-packages (from ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.1.6)
Requirement already satisfied: debugpy>=1.0 in d:\anaconda\lib\site-packages (from ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (1.5.1)
Requirement already satisfied: pywin32>=1.0 in d:\anaconda\lib\site-packages (from jupyter-core->nbconvert>=5.6.1->datapane) (302)
Requirement already satisfied: pickleshare in d:\anaconda\lib\site-packages (from ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in d:\anaconda\lib\site-packages (from ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (3.0.20)
Requirement already satisfied: backcall in d:\anaconda\lib\site-packages (from ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.2.0)
Requirement already satisfied: decorator in d:\anaconda\lib\site-packages (from ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (5.1.1)
Requirement already satisfied: jedi>=0.16 in d:\anaconda\lib\site-packages (from ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.18.1)
Requirement already satisfied: setuptools>=18.5 in d:\anaconda\lib\site-packages (from ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (63.4.1)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in d:\anaconda\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.8.3)
Requirement already satisfied: wcwidth in d:\anaconda\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.2.5)
Installing collected packages: orderedmultidict, multimethod, more-itertools, face, dulwich, dominate, datacommons, dacite, colorlog, backoff, requests-toolbelt, posthog, jaraco.functools, glom, furl, vega-datasets, datacommons-pandas, cheroot, ipynbname, datapane
Successfully installed backoff-2.2.1 cheroot-9.0.0 colorlog-6.7.0 dacite-1.8.0 datacommons-1.4.3 datacommons-pandas-0.0.3 datapane-0.16.4 dominate-2.7.0 dulwich-0.21.5 face-20.1.1 furl-2.1.3 glom-23.3.0 ipynbname-2021.3.2 jaraco.functools-3.6.0 more-itertools-9.1.0 multimethod-1.9.1 orderedmultidict-1.0.1 posthog-2.5.0 requests-toolbelt-0.10.1 vega-datasets-0.9.0
Note: you may need to restart the kernel to use updated packages.

In [8]:
import datapane as dp
import altair as alt

In [9]:
dp.DataTable(seattle_mk_df)

D:\Anaconda\lib\site-packages\datapane\common\df_processor.py:28: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(df.index, pd.Int64Index):

In [10]:
dp.DataTable(nyc_mk_df)

In [11]:
dp.DataTable(dc_mk_df)